### ISSUE TITLE
Create expense with no registered user

### ISSUE THREAD

**Issue by psyrus** [psyrus/home-expenses-backend#24]
When testing the frontend it was discovered that it is possible to create an expense entry with a null value for registered user:

![image](https://github.com/psyrus/home-expenses-backend/assets/8152287/08e4a14a-56ad-414d-8502-01ae15fa2ee9)

**Comment by Jerrif** [comment]
It seems like (the first half of) the solution to this is adding `nullable=False` to the `mapped_column()` call in `models.py`. Though now I'm wondering, shouldn't that apply to basically every field (except maybe `updated_at` and `description`)? You wouldn't want `category`, `expense_date`, `cost` etc to be null either right?

**Comment by Jerrif** [comment]
Ah, this seems like the second half of the solution.
https://stackoverflow.com/questions/57291723/sqlalchemy-can-i-map-an-empty-string-to-null-in-the-ddl-i-want-a-nullable-inte
